name: base-check

on: push

jobs:
  build-main:
    name: base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: 8.4
      - run: make install
      - run: make lint
      - run: make test

  SonarQube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: 8.4
          coverage: xdebug
      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress
      - name: gen key
        run: php artisan key:gen --env=testing
      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit tests --coverage-clover=coverage.xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@40f5b61913e891f9d316696628698051136015be
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}